---
- name: Add apt key by id from a keyserver
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: C2518248EEA14886

- name: Add apt repository
  apt_repository:
    filename: java-8-debian
    repo: "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main"

- name: Accept Java 8 License
  become: yes
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

- name: Install Oracle Java 8
  apt:
    update_cache: yes
    state: present
    pkg:
      - openjdk-8-jre-headless
      - ca-certificates
