- name: Create users and add him to groups
  user:
    name: "{{ item }}"
    group: "{{ item }}"
    append: yes
    shell: /bin/bash
  with_items:
    - admins
    - developers

- name: Set authorized key without validating the TLS/SSL certificates
  authorized_key:
    user: "{{ item }}"
    state: present
    key: https://github.com/marceloalmeida.keys
    validate_certs: False
  with_items:
    - admins
    - developers
